name: G4F-AddTime

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

permissions:
  contents: write
  actions: write

jobs:
  renew:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Private Repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/g4f-control
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Linux deps
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq xvfb libgbm1 libnss3 libatk1.0-0 libcups2 libdrm2 libxkbcommon0

      - name: Install Python deps
        run: |
          pip install -r requirements.txt

      - name: Run Script
        env:
          DISPLAY: :99
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &
          python g4f.py

      - name: Commit
        if: always()
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          git add README.md storage_state.json || true
          git commit -m "update state [skip ci]" || echo "No changes"
          git push origin ${{ github.ref_name }} || echo "Push failed"

      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: g4f-results
          path: "*.png"